

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "-t","60", "npm", "start"]
    env_file: .env
    networks:
      - server

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SkillMatchAI
    ports:
      - "5432:5432"
    networks:
      - server

networks:
  server:
    driver: bridge
