name: Angular CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: ./Client/Jobsite
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        working-directory: ./Client/Jobsite
        run: ng build --configuration production

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: Client/Jobsite/dist/jobsite

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist

      - name: Show Build Files
        run: ls -R ./dist

      - name: Deploy
        id: deploy
        uses: ./.github/actions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: dicksonndumia
          dist-folder: ./dist
          bucket-region: us-east-1

      - name: Output Deployment URL
        run: echo "Live URL: ${{ steps.deploy.outputs.website-url }}"
